# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Color' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Color
  pod 'RAMAnimatedTabBarController'
  pod ‘RxSwift’, ‘6.2.0’
  pod 'RxCocoa', '6.2.0'
  pod 'CircleMenu'
  pod 'Alamofire', '~> 5.4'
  pod 'SimpleCheckbox'
  pod 'FloatingPanel'
  pod 'Hashtags'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Moya/RxSwift', '~> 15.0'
end
